#+title: Placeholder title: a game
#+author: I Think Therefore I Jam

#+options: toc:nil num:nil

#+latex_header: \usepackage[margin=2cm]{geometry}

* General description

This will be a simple interactive fiction game, strongly inspired by the Stanley Parable.
You control a regular white-collar worker at a generic sterile inhospitable office, working overtime (unpaid of course). 
The main gameplay will be provided by minigames that occur across a strongly linear story, with each one designed to throw off the player's expectations.
The story will be driven by an omniscient disembodied narrator who will be providing scathing commentary over each beat. Fourth wall breaks will be quite frequent, and meta humour will be a staple.

* Themes

\paragraph{Comic} The entire game is expected to be comical, bordering on bizarre. The main task will be writing scripts for comics. The Comic family of fonts (including the classic Comic Sans) will be used almost everywhere. Frequent puns about comics will be dropped in narration (this will be true for all three themes, hopefully).

\paragraph{Light} Light will be the primary antagonist of the game. A lot of the actions of the protagonist will be in response to losing out on some light that is essential to your work. The humour would make the game light-hearted, despite not being for the light-hearted.

\paragraph{Twist} The plot will twist, the world will twist, minigames might involve twisting threads together as a wick for lighting. Puns of course will be aplenty.


* Appendix: Team details

\begin{enumerate}
\item\label{item:1} Vishesh Saraswat (=visheshs2910@gmail.com=, @justvishesh)
\item\label{item:2} Druhan Shah (=druhanrshah@gmail.com=, @druhanrshah)
\item\label{item:3} Nandini Chakaravarthy (=nandini.c@research.iiit.ac.in=, @chakaravarthy51234)
\item\label{item:4} Kimaya Arora (=kimaya.arora.10@gmail.com=, @kimaya.arora)
\item\label{item:5} Arnav Gupta (=arnavg@duck.com=, @wintersolstice)
\end{enumerate}
